name: CMake

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up python
      uses: actions/setup-python@v1
      with:
        python-version: "3.6.x"
        architecture: "x64"
    - name: install gcc-c++
      run: |
        sudo apt-get update && sudo apt-get install -y gcc-multilib

    - name: Install conan && conan package tools
      run: |
        python -m pip install --upgrade pip
        pip install conan
        pip install conan_package_tools

    - name: third-party
      run: |
        conan install .

    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}
      run: cmake . -DCMAKE_INSTALL_PREFIX=${{runner.workspace}}/output

    - name: Build
      working-directory: ${{runner.workspace}}
      shell: bash
      run: |
        cmake --build .
        make --install .

    - name: Release
      uses: actions/upload-artifact@v2
      with:
        path: ${{runner.workspace}}/output

